services:
  postgresdb:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: password_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/password_manager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  pg_data: