spring.application.name=PasswordManager

#db
spring.datasource.url=jdbc:postgresql://localhost:5432/password_manager
spring.datasource.username=postgres
spring.datasource.password=sabitha
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#jwt
jwt.secret=_teeqkRR2z5q•••••••••••••••••••&sW6?N.j#)B@
jwt.expiration=3600000 

#redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=300000

