spring.application.name=PasswordManager

# Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.bcekwynpkjopzfgpcyhm
spring.datasource.password=Sabitha@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=_teeqkRR2z5q•••••••••••••••••••&sW6?N.j#)B@
jwt.expiration=3600000