spring.application.name=PasswordManager

# PostgreSQL DB
spring.datasource.url=jdbc:postgresql://localhost:5432/password_manager
spring.datasource.username=postgres
spring.datasource.password=sabitha
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=_teeqkRR2z5q•••••••••••••••••••&sW6?N.j#)B@
jwt.expiration=3600000